# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('search_index', djorm_pgfulltext.fields.VectorField()),
            ],
        ),
    ]
